Skiffie/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Core.Objects.DataClasses;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Runtime.Serialization;

namespace Skiffie.Models
{

    public class Schedule
    {
        [Required]
        public virtual int ScheduleId { get; set; }

        //set whether this is the default schedule or not.
        [Required]
        [Display(Name = "Default Weekly Schedule")]
        public virtual bool DefaultOption { get; set; }

        //otherwise, use a specific date.
        [Required]
        [DataType(DataType.Date)]
        public virtual DateTime Date { get; set; }

        //and the specific openings available.
        public virtual List<Openings> Openings { get; set; }

        //this is only really used for default dates so we can disable old ones.
        public virtual bool Active { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DefaultOption == false && Date == null)
            {
                yield return new ValidationResult("Date is required!");
            }
        }

        //filter to specific openings.
        public Schedule ScheduleWithFilter(DateTime targetDate, TimeSlot timeSlot = null, InstallZone installZone = null)
        {
            Openings.Clear();
            Openings = AvailableOpenings(targetDate, timeSlot, installZone);

            return (this);
        }

        //filter out openings.
        private List<Openings> FilterOpenings(DateTime targetDate, TimeSlot timeSlot, InstallZone installZone)
        {
            SkiffieContext db = new SkiffieContext();
            IEnumerable<Appointment> Apps = db.Appointments.Where(x => x.Date == targetDate);
            List<Openings> SelectedOpenings = new List<Openings>();

            //we want to only pick days that are relevant.
            int day;
            if (DefaultOption)
            {
                day = (int)targetDate.DayOfWeek;
            }
            else
            {
                day = -1;
            }

            SelectedOpenings = db.Openings.Where(x => x.ScheduleID == ScheduleId && x.Day == day).OrderBy(x => x.InstallZone.Name).ThenBy(x => x.TimeSlot.Name).ToList();

            if (timeSlot != null)
            {
                SelectedOpenings = SelectedOpenings.Where(x => x.TimeSlotId == timeSlot.TimeSlotID).ToList();
                Apps = Apps.Where(x => x.TimeSlot == timeSlot);
            }
            if (installZone != null)
            {
                SelectedOpenings = SelectedOpenings.Where(x => x.InstallZoneId == installZone.InstallZoneId).ToList();
                Apps = Apps.Where(x => x.Customer.Tower.InstallZone == installZone);
            }

            return SelectedOpenings;
        }

        //filter available openings only.
        private List<Openings> AvailableOpenings(DateTime targetDate, TimeSlot timeSlot, InstallZone installZone) 
        {
            SkiffieContext db = new SkiffieContext();
            IEnumerable<Appointment> Apps = db.Appointments.Where(x => x.Date == targetDate && x.CurrentState != Appointment.AppointmentState.Cancelled 
                && x.CurrentState != Appointment.AppointmentState.Failed && x.CurrentState != Appointment.AppointmentState.NeedsReschedule);
            List<Openings> SelectedOpenings = FilterOpenings(targetDate,timeSlot,installZone);
            foreach (var x in SelectedOpenings)
            {
                x.AvailableAmount = x.Amount;
            }

            foreach (var x in Apps)
            {
                try
                {
                    SelectedOpenings.DefaultIfEmpty(null).FirstOrDefault(y => y.InstallZoneId == x.Customer.Tower.InstallZoneId && y.TimeSlotId == x.TimeSlotID).AvailableAmount--;
                }
                catch (NullReferenceException e)
                {
                    var y = 123123;
                }
            }

            return SelectedOpenings;
        }

        public Schedule Clone(Schedule schedule)
        {
            //lazy cloning, for the time being. Definitely need to improve this later.

            schedule.DefaultOption = this.DefaultOption;
            schedule.Date = this.Date;
            schedule.Active = this.Active;
            schedule.Openings = new List<Openings>();

            var OpeningsForMe = Openings.Where(x => x.ScheduleID == ScheduleId).ToList();
            for (int i = 0; i < OpeningsForMe.Count; i++)
            {
                Openings myOpening = new Openings();

                myOpening = OpeningsForMe[i].Clone(myOpening);

                schedule.Openings.Add(myOpening);
            }

            return schedule;
        }

    }

    public class Openings
    {
        public virtual int OpeningsID { get; set; }

        //assign to a schedule.
        [Required]
        public virtual int ScheduleID { get; set; }
        public virtual Schedule Schedule { get; set; }

        [Required]
        public virtual int InstallZoneId { get; set; }
        public virtual InstallZone InstallZone { get; set; }

        [Required]
        public virtual int TimeSlotId { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }

        [Required]
        [Range(0,100)]
        public virtual int Amount { get; set; }
        public virtual int AvailableAmount { get; set; }

        [Required]
        [Range(-1,7)]
        public virtual int Day { get; set; }

        public Openings Clone(Openings Opening)
        {
            //Openings Opening = new Openings();
            Opening.InstallZoneId = InstallZoneId;
            Opening.InstallZone = InstallZone;
            Opening.TimeSlotId = TimeSlotId;
            Opening.TimeSlot = TimeSlot;
            Opening.Amount = Amount;
            Opening.AvailableAmount = AvailableAmount;
            Opening.Day = Day;

            return (Opening);
        }
    }
}

Skiffie/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Skiffie.Models;

namespace Skiffie.Controllers
{
    [Authorize]
    public class SchedulesController : Controller
    {
        private SkiffieContext db = new SkiffieContext();

        // GET: Schedules
        public ActionResult Index()
        {
            return View(db.Schedules.OrderByDescending(x=>x.DefaultOption).ThenBy(x=>x.Date).ToList());
        }

        public ActionResult SingleDay(){
            ViewBag.InstallZones = db.InstallZones.OrderBy(x => x.Name);
            ViewBag.TimeSlots = db.TimeSlots.OrderBy(x => x.Name);

            return PartialView("SingleDaySchedule", new Openings());
        }

        public ActionResult Week(){
            ViewBag.InstallZones = db.InstallZones.OrderBy(x => x.Name);
            ViewBag.TimeSlots = db.TimeSlots.OrderBy(x => x.Name);

            return PartialView("WeekSchedule", new Openings());
        }

        // GET: Schedules/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Schedules/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.TimeSlots = db.TimeSlots.OrderBy(x => x.TimeSlotID);
            ViewBag.Zones = db.InstallZones.OrderBy(x => x.Name);
            Schedule model = new Schedule();
            model.Date = DateTime.Today;
            return View("Create", model);
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ScheduleId,DefaultOption,Date")] Schedule schedule, List<int> Day, List<int> InstallZoneId, List<int> TimeSlotId, List<int> Amount)
        { 
            HttpContext.Request.InputStream.Position = 0;
            var result = new System.IO.StreamReader(HttpContext.Request.InputStream).ReadToEnd();

            //specify how many values we should see if it's a specific date.
            int specificDayCount = db.InstallZones.Count() * db.TimeSlots.Count();

            //Specify how many vlaues we should see if it's a full week.
            int weekCount = specificDayCount*7;

            //prepare everything in a nice class list.
            List<ScheduledDate> schedules = CreateDate(Day, InstallZoneId, TimeSlotId, Amount);

            if (ModelState.IsValid && schedules != null)
            {
                bool issueFound = false;
                //now do a check on the date count.
                if (schedule.DefaultOption == false)
                {
                    List<ScheduledDate> daysToWork = schedules.Where(x => x.Day == -1).ToList();
                    //set the days to add 
                    //check if the amount of days are right.
                    if (daysToWork.Count == specificDayCount)
                    {
                        schedule.Openings = new List<Openings>();
                        foreach (ScheduledDate x in daysToWork)
                        {
                            schedule.Openings.Add(new Openings
                            {
                                Schedule = schedule,
                                Amount = x.Amount,
                                Day = x.Day,
                                InstallZoneId = x.Zone,
                                InstallZone = db.InstallZones.First(y => y.InstallZoneId == x.Zone),
                                TimeSlotId = x.TimeSlot,
                                TimeSlot = db.TimeSlots.First(y => y.TimeSlotID == x.TimeSlot)
                            });
                        }
                    }
                    else
                    {
                        issueFound = true;
                    }
                }
                else
                {
                    List<ScheduledDate> daysToWork = schedules.Where(x => x.Day > -1).ToList();
                    //check if the days are right.
                    if (daysToWork.Count == weekCount)
                    {
                        schedule.Openings = new List<Openings>();
                        //make sure only one default state is active at any time.
                        foreach (var z in db.Schedules.Where(x => x.DefaultOption == true).ToList())
                        {
                            foreach (var y in z.Openings.ToList())
                            {
                                db.Openings.Remove(y);
                            }
                            db.Schedules.Remove(z);
                        }
                        foreach (ScheduledDate x in daysToWork)
                        {
                            schedule.Openings.Add(new Openings
                            {
                                Schedule = schedule,
                                Amount = x.Amount,
                                Day = x.Day,
                                InstallZoneId = x.Zone,
                                InstallZone = db.InstallZones.First(y => y.InstallZoneId == x.Zone),
                                TimeSlotId = x.TimeSlot,
                                TimeSlot = db.TimeSlots.First(y => y.TimeSlotID == x.TimeSlot)
                            });
                        }
                    }
                    else
                    {
                        issueFound = true;
                    }
                }
                if (issueFound) {
                    return View(schedule);
                }
                schedule.Active = true;
                db.Schedules.Add(schedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TimeSlots = db.TimeSlots.OrderBy(x => x.TimeSlotID);
            ViewBag.Zones = db.InstallZones.OrderBy(x => x.Name);

            return View(schedule);
        }

        // GET: Schedules/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Schedule schedule = db.Schedules.Find(id);

            foreach (var opening in schedule.Openings.ToList())
            {
                db.Openings.Remove(opening);
            }

            db.Schedules.Remove(schedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private class ScheduledDate {
            public int Day { get; set; }
            public int TimeSlot { get; set; }
            public int Zone { get; set; }
            public int Amount { get; set; }
        }

        private List<ScheduledDate> CreateDate(List<int> Days, List<int> Zones, List<int> Times, List<int> Amounts) {
            if (Days.Count == Zones.Count && Zones.Count == Times.Count && Times.Count == Amounts.Count)
            {
                List<ScheduledDate> returnValue = new List<ScheduledDate>();
                for (int i = 0; i < Days.Count; i++)
                {
                    returnValue.Add(new ScheduledDate
                    {
                        Day = Days[i],
                        TimeSlot = Times[i],
                        Zone = Zones[i],
                        Amount = Amounts[i]
                    });
                }
                return returnValue;
            }
            else
            {
                return null;
            }
        }
    }
}

Skiffie/Views/Schedules/Create.cshtml
@model Skiffie.Models.Schedule

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Schedule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DefaultOption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DefaultOption)
                    @Html.ValidationMessageFor(model => model.DefaultOption, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control date-picker", @value=DateTime.Today.ToString() } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group specificDate">
            <div class="form-group specificDate">
                <label class="control-label col-md-2">
                    Specific Date:
                </label>
                @{Html.RenderAction("SingleDay", "Schedules");}
            </div>
        </div>

        <div class="form-group nonSpecificDate" hidden>
            <div class="form-group">
                @{Html.RenderAction("Week", "Schedules");}
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Skiffie/Views/Schedules/Delete.cshtml
@model Skiffie.Models.Schedule

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DefaultOption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultOption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Skiffie/Views/Schedules/Details.cshtml
@model Skiffie.Models.Schedule

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DefaultOption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DefaultOption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ScheduleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Skiffie/Views/Schedules/Edit.cshtml
@model Skiffie.Models.Schedule

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Schedule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ScheduleId)

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultOption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DefaultOption)
                    @Html.ValidationMessageFor(model => model.DefaultOption, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Skiffie/Views/Schedules/Index.cshtml
@model IEnumerable<Skiffie.Models.Schedule>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DefaultOption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DefaultOption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.ScheduleId })
        </td>
    </tr>
}

</table>

Skiffie/Views/Schedules/_DefaultSchedule.cshtml
@model Skiffie.Models.Schedule